// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer,
} from "spacetimedb";
import { TeamColor } from "./types";

export default __t.row({
    id: __t.u64().primaryKey(),
    redPlayerIdentity: __t.identity().name("red_player_identity"),
    redPlayerPresent: __t.bool().name("red_player_present"),
    redPlayerKeepAlive: __t.bool().name("red_player_keep_alive"),
    bluePlayerIdentity: __t.identity().name("blue_player_identity"),
    bluePlayerPresent: __t.bool().name("blue_player_present"),
    bluePlayerKeepAlive: __t.bool().name("blue_player_keep_alive"),
    scheduledAt: __t.scheduleAt().name("scheduled_at"),
    get currentTurn() {
        return TeamColor.name("current_turn");
    },
    started: __t.bool(),
    get winner() {
        return __t.option(TeamColor);
    },
});
