// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer,
} from "spacetimedb";
import { PieceType, TeamColor, PieceWinner } from "./types";

export default __t.row({
    game: __t.u64().primaryKey(),
    get attackerTeam() {
        return TeamColor.name("attacker_team");
    },
    piece: __t.u64(),
    get pieceType() {
        return PieceType.name("piece_type");
    },
    attackedPiece: __t.u64().name("attacked_piece"),
    get attackedPieceType() {
        return PieceType.name("attacked_piece_type");
    },
    get winner() {
        return PieceWinner;
    },
});
