// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer,
} from "spacetimedb";
import { PieceType, TeamColor, PieceWinner } from "./types";

export default __t.row({
    game: __t.u64().primaryKey(),
    get attackerTeam() {
        return TeamColor.name("attacker_team");
    },
    attackerPiece: __t.u64().name("attacker_piece"),
    get attackerPieceType() {
        return PieceType.name("attacker_piece_type");
    },
    defenderPiece: __t.u64().name("defender_piece"),
    get defenderPieceType() {
        return PieceType.name("defender_piece_type");
    },
    get winner() {
        return PieceWinner;
    },
});
