// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer,
} from "spacetimedb";

export const BoardPiece = __t.object("BoardPiece", {
    id: __t.u64(),
    game: __t.u64(),
    get position() {
        return HexPosition;
    },
    get pieceType() {
        return PieceType;
    },
    get team() {
        return TeamColor;
    },
});
export type BoardPiece = __Infer<typeof BoardPiece>;

export const Game = __t.object("Game", {
    id: __t.u64(),
    redPlayerIdentity: __t.identity(),
    redPlayerPresent: __t.bool(),
    redPlayerKeepAlive: __t.bool(),
    bluePlayerIdentity: __t.identity(),
    bluePlayerPresent: __t.bool(),
    bluePlayerKeepAlive: __t.bool(),
    scheduledAt: __t.scheduleAt(),
    get currentTurn() {
        return TeamColor;
    },
    started: __t.bool(),
    get winner() {
        return __t.option(TeamColor);
    },
});
export type Game = __Infer<typeof Game>;

export const GameInfo = __t.object("GameInfo", {
    get game() {
        return Game;
    },
    get team() {
        return TeamColor;
    },
    get pieces() {
        return __t.array(PublicPiece);
    },
});
export type GameInfo = __Infer<typeof GameInfo>;

export const HexPosition = __t.object("HexPosition", {
    col: __t.i32(),
    row: __t.i32(),
});
export type HexPosition = __Infer<typeof HexPosition>;

export const Leaderboard = __t.object("Leaderboard", {
    get leaderboard() {
        return __t.array(User);
    },
});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const PieceCaptureEvent = __t.object("PieceCaptureEvent", {
    game: __t.u64(),
    get attackerTeam() {
        return TeamColor;
    },
    piece: __t.u64(),
    get pieceType() {
        return PieceType;
    },
    attackedPiece: __t.u64(),
    get attackedPieceType() {
        return PieceType;
    },
    get winner() {
        return PieceWinner;
    },
});
export type PieceCaptureEvent = __Infer<typeof PieceCaptureEvent>;

// The tagged union or sum type for the algebraic type `PieceType`.
export const PieceType = __t.enum("PieceType", {
    Bomb: __t.unit(),
    Spy: __t.unit(),
    Scout: __t.unit(),
    Miner: __t.unit(),
    Sergeant: __t.unit(),
    Lieutenant: __t.unit(),
    Captain: __t.unit(),
    Major: __t.unit(),
    Colonel: __t.unit(),
    General: __t.unit(),
    Marshal: __t.unit(),
    Flag: __t.unit(),
});
export type PieceType = __Infer<typeof PieceType>;

// The tagged union or sum type for the algebraic type `PieceWinner`.
export const PieceWinner = __t.enum("PieceWinner", {
    Attacker: __t.unit(),
    Attacked: __t.unit(),
    Draw: __t.unit(),
});
export type PieceWinner = __Infer<typeof PieceWinner>;

export const PublicPiece = __t.object("PublicPiece", {
    id: __t.u64(),
    get position() {
        return HexPosition;
    },
    get pieceType() {
        return __t.option(PieceType);
    },
    get team() {
        return TeamColor;
    },
});
export type PublicPiece = __Infer<typeof PublicPiece>;

export const StagingPiece = __t.object("StagingPiece", {
    id: __t.u64(),
    user: __t.identity(),
    get position() {
        return HexPosition;
    },
    get pieceType() {
        return PieceType;
    },
});
export type StagingPiece = __Infer<typeof StagingPiece>;

// The tagged union or sum type for the algebraic type `TeamColor`.
export const TeamColor = __t.enum("TeamColor", {
    Red: __t.unit(),
    Blue: __t.unit(),
});
export type TeamColor = __Infer<typeof TeamColor>;

export const User = __t.object("User", {
    identity: __t.identity(),
    name: __t.string(),
    online: __t.bool(),
    gamesPlayed: __t.u32(),
    gamesWon: __t.u32(),
    gamesLoss: __t.u32(),
});
export type User = __Infer<typeof User>;
