// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import JoinGameReducer from "../join_game_reducer";
import KeepAliveReducer from "../keep_alive_reducer";
import MovePieceReducer from "../move_piece_reducer";
import QuitGameReducer from "../quit_game_reducer";
import SetUserNameReducer from "../set_user_name_reducer";
import StagingClearPieceReducer from "../staging_clear_piece_reducer";
import StagingSetPieceReducer from "../staging_set_piece_reducer";

export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type KeepAliveParams = __Infer<typeof KeepAliveReducer>;
export type MovePieceParams = __Infer<typeof MovePieceReducer>;
export type QuitGameParams = __Infer<typeof QuitGameReducer>;
export type SetUserNameParams = __Infer<typeof SetUserNameReducer>;
export type StagingClearPieceParams = __Infer<typeof StagingClearPieceReducer>;
export type StagingSetPieceParams = __Infer<typeof StagingSetPieceReducer>;
